#Configuração destinada ao ambiente de desenvolvimento, os demais perfis hedarão deste
spring:
  application.name: portal-compras
  jmx.enabled: false

#DATA SOURCE
  datasource:
    hikari.pool-name: ${spring.application.name}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 3
    url: jdbc:postgresql://127.0.0.1:5432/portal-compras
    username: postgres
    password: postgres

#JPA
  jpa:
    hibernate:
        ddl-auto: update
        naming:
            implicit-strategy: br.org.pti.fpti_base.application.configuration.ConstraintsImplicitNamingStrategy
    show-sql: true
    open-in-view: false
    properties:
      hibernate.dialect: br.org.pti.fpti_base.infrastructure.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.default_schema: public
      org.hibernate.envers.audit_table_suffix: _audited
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type
      org.hibernate.envers.default_schema: auditing

#STATIC RESOURCES
  resources.static-locations: classpath:/META-INF/resources/
  resources.chain:
    cache: false
    strategy.content.enabled: true
    strategy.content.paths: /**
    
#MAIL
  mail:
    host: info-fpti.fpti.pti.org.br
    port: 587
    username: basi2t@ptibasit.fpti.pti.org.br
    password: 0QTxaj1Ni7yok82h8we9
    #from> pego na classe AsyncMailRepository
    from: basi2t@ptibasit.fpti.pti.org.br
    properties:
      #mail.smtp.auth: true
      mail.transport.protocol: smtp
      mail.smtp.starttls.enable: true
      #mail.smtp.starttls.required: true
      #mail.smtp.ssl.enable: false
      mail.smtps.debug: true
      mail.smtp.debug: true
      mail.debug: true
      #mail.connectiontimeout: 10000
      
#THYMELEAF
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/META-INF/resources/
    suffix: .html

#FLYWAY
  flyway:
    enabled: true
    check-location: true
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix: v
    
#SECURITY ACTUATORS
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

#WEB CONTAINER
server:
  servlet:    
    context-path: 
    compression.enabled: true
    session.persistent: true
    session.timeout: 999999999
    
    
#LOGGING
logging.level:
  org.hibernate: INFO
  org.directwebremoting: INFO
  org.springframework.web: INFO
  org.springframework.context.support: INFO
  org.springframework.security: INFO
  
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

