#Configuração destinada ao ambiente de production
#GENERAL
spring:

#DATA SOURCE
  datasource:
    url: jdbc:postgresql://localhost:5432/CHANGE
    username: CHANGE
    password: CHANGE
    hikari.maximum-pool-size: 3

#JPA
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    
#STATIC RESOURCES
  resources.chain:
    cache: false
    
#FLYWAY
  flyway:
    enabled: true